export type Product = {
  id: string;
  title: string;
  slug: string;
  sku: string;
  product_type: string;
  size_ft: string;
  condition: string;
  condition_grade?: string | null;
  color?: string | null;
  depot?: string | null;
  price_gross: number;
  currency?: string | null;
  availability?: string | null;
  quantity?: number | null;
  ext_length_mm?: number | null;
  ext_width_mm?: number | null;
  ext_height_mm?: number | null;
  int_length_mm?: number | null;
  int_width_mm?: number | null;
  int_height_mm?: number | null;
  door_width_mm?: number | null;
  door_height_mm?: number | null;
  tare_weight_kg?: number | null;
  max_gross_weight_kg?: number | null;
  payload_kg?: number | null;
  volume_m3?: number | null;
  csc_status?: string | null;
  wwt_status?: boolean | null;
  cargo_worthy?: boolean | null;
  floor_type?: string | null;
  lockbox?: boolean | null;
  vents?: boolean | null;
  forklift_pockets?: boolean | null;
  main_image?: string | null;
  additional_images?: string[] | null;
  short_description?: string | null;
  description?: string | null;
  is_purchasable?: boolean | null;
  featured?: boolean | null;
  created_date?: string;
  updated_date?: string;
  family_id?: string | null;
  colors?: string[] | null;
};
