"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState, useSyncExternalStore } from "react";
import { Building2, CheckCircle2, CreditCard, MapPin, PackageCheck, Truck } from "lucide-react";
import { CART_EVENT, CART_KEY, type CartItem, readCart, writeCart } from "@/lib/cart";
import type { Locale } from "@/lib/i18n";
import { href } from "@/lib/routes";
import { countryOptions } from "@/lib/shipping-countries";

type Copy = {
  title: string; intro: string; step1: string; step2: string; step3: string; private: string; business: string;
  name: string; company: string; vatId: string; email: string; phone: string; street: string; number: string; address2: string; postcode: string; city: string; country: string;
  address: string; unloading: string; site: string; curbside: string; curbsideText: string; crane: string; craneText: string; date: string; access: string; accessPlaceholder: string;
  order: string; net: string; vat: string; gross: string; taxPending: string; shipping: string; shippingPending: string; totalPending: string; bulk: string;
  invoice: string; invoiceText: string; sepa: string; sepaText: string; terms: string; privacy: string; submit: string; submitting: string;
  empty: string; shop: string; success: string; successText: string; error: string; reference: string; euVat: string; euVatNote: string; euTotal: string;
};

const copies: Record<Locale, Copy> = {
  de: { title: "Kasse", intro: "Bestellen Sie Ihre Container direkt. Lieferkosten und der endgültige Steuerbetrag werden anhand Ihrer Angaben geprüft, bevor Sie zahlen.", step1: "1. Kontakt & Rechnung", step2: "2. Lieferung & Entladung", step3: "3. Prüfung & Zahlungsart", private: "Privatkunde", business: "Geschäftskunde", name: "Vor- und Nachname", company: "Unternehmen", vatId: "USt-IdNr. (optional)", email: "E-Mail", phone: "Telefon", street: "Straße", number: "Hausnummer", address2: "Adresszusatz (optional)", postcode: "PLZ", city: "Ort / Region", country: "Lieferland", address: "Lieferadresse", unloading: "Entladung", site: "Zufahrt & Aufstellort", curbside: "Bordsteinkante / Selbstentladung", curbsideText: "Der Container wird angeliefert; eine geeignete Entladung wird bauseits organisiert.", crane: "Entladung per Kran erforderlich", craneText: "Wir prüfen Kranfahrzeug, Zufahrt und sichere Aufstellung.", date: "Gewünschter Liefertermin (optional)", access: "Zufahrt und Aufstellort", accessPlaceholder: "Zufahrtsbreite, Hindernisse, Untergrund, Ansprechpartner vor Ort …", order: "Ihre Bestellung", net: "Netto", vat: "MwSt. (19 %)", gross: "Warenwert inkl. MwSt.", taxPending: "Der endgültige Steuerbetrag wird für das Zielland geprüft.", shipping: "Lieferung", shippingPending: "Wird anhand von PLZ/Region, Entladung, Anzahl, Größen und Zufahrt geprüft.", totalPending: "Endbetrag nach Lieferprüfung", bulk: "Bei mehreren Containern prüfen wir eine gebündelte Fracht und mögliche Preisabstimmung.", invoice: "Rechnung zur Bestätigung", invoiceText: "Sie erhalten nach Prüfung den endgültigen Betrag und bestätigen anschließend.", sepa: "SEPA-Zahlungsanforderung", sepaText: "Wenn alles passt, erhalten Sie Rechnung und SEPA-Zahlungsdaten. Zahlen Sie erst nach Bestätigung.", terms: "Ich akzeptiere die", privacy: "Ich habe die Datenschutzerklärung gelesen.", submit: "Bestellung zur Prüfung senden", submitting: "Wird gesendet …", empty: "Ihr Warenkorb ist leer.", shop: "Container auswählen", success: "Bestellung eingegangen", successText: "Wir prüfen Verfügbarkeit, Steuer und Lieferung und senden anschließend den bestätigten Endbetrag sowie die gewählte Zahlungsinformation.", error: "Die Bestellung konnte nicht gesendet werden. Bitte versuchen Sie es erneut oder kontaktieren Sie uns.", reference: "Referenz", euVat: "MwSt. (vorläufig 0 %)", euVatNote: "Innergemeinschaftliche B2B-Lieferung: 0 % MwSt. erst nach erfolgreicher Prüfung der EU-USt-IdNr. und des Transportnachweises.", euTotal: "Vorläufiger Warenwert" },
  en: { title: "Checkout", intro: "Order your containers directly. Delivery and final tax treatment are reviewed from your details before payment.", step1: "1. Contact & billing", step2: "2. Delivery & unloading", step3: "3. Review & payment method", private: "Private customer", business: "Business customer", name: "Full name", company: "Company", vatId: "VAT ID (optional)", email: "Email", phone: "Phone", street: "Street", number: "House number", address2: "Address line 2 (optional)", postcode: "Postcode", city: "City / Region", country: "Delivery country", address: "Delivery address", unloading: "Unloading", site: "Access & placement site", curbside: "Curbside / self-unloading", curbsideText: "The container is delivered; you arrange suitable unloading equipment on site.", crane: "Crane unloading required", craneText: "We review crane vehicle, access and safe placement.", date: "Preferred delivery date (optional)", access: "Access and placement site", accessPlaceholder: "Access width, obstacles, surface and on-site contact …", order: "Your order", net: "Net", vat: "VAT (19%)", gross: "Goods incl. VAT", taxPending: "Final destination-country tax treatment will be reviewed.", shipping: "Delivery", shippingPending: "Reviewed from postcode/region, unloading, quantity, sizes and site access.", totalPending: "Final total after delivery review", bulk: "For multiple containers we review consolidated freight and possible price adjustments.", invoice: "Invoice for confirmation", invoiceText: "Receive the final reviewed amount and confirm before payment.", sepa: "SEPA payment request", sepaText: "If everything is correct, you receive the invoice and SEPA payment details. Pay only after confirmation.", terms: "I accept the", privacy: "I have read the privacy policy.", submit: "Send order for review", submitting: "Sending …", empty: "Your cart is empty.", shop: "Choose containers", success: "Order received", successText: "We will review availability, tax and delivery, then send the confirmed total and your chosen payment information.", error: "The order could not be sent. Please try again or contact us.", reference: "Reference", euVat: "VAT (provisional 0%)", euVatNote: "Intra-EU B2B supply: 0% VAT applies only after successful EU VAT ID and transport-evidence checks.", euTotal: "Provisional goods total" },
  nl: { title: "Afrekenen", intro: "Bestel containers direct. Levering en belasting worden vóór betaling gecontroleerd.", step1: "1. Contact & factuur", step2: "2. Levering & lossen", step3: "3. Controle & betaalwijze", private: "Particulier", business: "Zakelijk", name: "Volledige naam", company: "Bedrijf", vatId: "Btw-nummer (optioneel)", email: "E-mail", phone: "Telefoon", street: "Straat", number: "Huisnummer", address2: "Adresregel 2 (optioneel)", postcode: "Postcode", city: "Plaats / Regio", country: "Land", address: "Afleveradres", unloading: "Lossen", site: "Toegang & plaatsing", curbside: "Stoeprand / zelf lossen", curbsideText: "U organiseert geschikte losapparatuur op locatie.", crane: "Lossen met kraan", craneText: "Wij controleren kraanwagen, toegang en veilige plaatsing.", date: "Gewenste datum (optioneel)", access: "Toegang en plaatsing", accessPlaceholder: "Breedte, obstakels, ondergrond en contactpersoon …", order: "Uw bestelling", net: "Netto", vat: "Btw (19%)", gross: "Goederen incl. btw", taxPending: "De definitieve belasting wordt gecontroleerd.", shipping: "Levering", shippingPending: "Wordt gecontroleerd op postcode, lossen, aantal, maten en toegang.", totalPending: "Eindtotaal na leveringscontrole", bulk: "Bij meerdere containers controleren we gecombineerde vracht en prijsafstemming.", invoice: "Factuur ter bevestiging", invoiceText: "U ontvangt het definitieve bedrag en bevestigt vóór betaling.", sepa: "SEPA-betaalverzoek", sepaText: "U ontvangt factuur en SEPA-gegevens na bevestiging.", terms: "Ik accepteer de", privacy: "Ik heb het privacybeleid gelezen.", submit: "Bestelling ter controle verzenden", submitting: "Verzenden …", empty: "Uw winkelwagen is leeg.", shop: "Containers kiezen", success: "Bestelling ontvangen", successText: "Wij controleren beschikbaarheid, belasting en levering en sturen daarna het bevestigde totaal.", error: "De bestelling kon niet worden verzonden.", reference: "Referentie", euVat: "Btw (voorlopig 0%)", euVatNote: "Intracommunautaire B2B-levering: 0% pas na controle van btw-nummer en vervoer.", euTotal: "Voorlopig goederentotaal" },
  it: { title: "Checkout", intro: "Ordina direttamente. Consegna e imposte vengono verificate prima del pagamento.", step1: "1. Contatto e fattura", step2: "2. Consegna e scarico", step3: "3. Verifica e pagamento", private: "Privato", business: "Azienda", name: "Nome completo", company: "Azienda", vatId: "Partita IVA (opzionale)", email: "Email", phone: "Telefono", street: "Via", number: "Numero civico", address2: "Riga indirizzo 2 (opzionale)", postcode: "CAP", city: "Città / Regione", country: "Paese", address: "Indirizzo di consegna", unloading: "Scarico", site: "Accesso e posa", curbside: "Bordo strada / scarico autonomo", curbsideText: "Organizzi attrezzature idonee per lo scarico.", crane: "Scarico con gru", craneText: "Verifichiamo autocarro, accesso e posa sicura.", date: "Data preferita (opzionale)", access: "Accesso e area di posa", accessPlaceholder: "Larghezza, ostacoli, fondo e referente …", order: "Il tuo ordine", net: "Netto", vat: "IVA (19%)", gross: "Merce IVA inclusa", taxPending: "L'imposta finale sarà verificata.", shipping: "Consegna", shippingPending: "Verificata da CAP, scarico, quantità, misure e accesso.", totalPending: "Totale finale dopo verifica", bulk: "Per più container verifichiamo trasporto combinato e adeguamenti.", invoice: "Fattura da confermare", invoiceText: "Ricevi l'importo finale e confermi prima del pagamento.", sepa: "Richiesta di pagamento SEPA", sepaText: "Ricevi fattura e dati SEPA dopo la conferma.", terms: "Accetto i", privacy: "Ho letto l'informativa privacy.", submit: "Invia ordine per verifica", submitting: "Invio …", empty: "Il carrello è vuoto.", shop: "Scegli i container", success: "Ordine ricevuto", successText: "Verificheremo disponibilità, imposte e consegna, quindi invieremo il totale confermato.", error: "Impossibile inviare l'ordine.", reference: "Riferimento", euVat: "IVA (0% provvisorio)", euVatNote: "Fornitura B2B intracomunitaria: 0% dopo verifica di partita IVA e trasporto.", euTotal: "Totale merce provvisorio" },
  cs: { title: "Pokladna", intro: "Objednejte přímo. Dopravu a daň ověříme před platbou.", step1: "1. Kontakt a faktura", step2: "2. Doprava a vykládka", step3: "3. Kontrola a platba", private: "Soukromý zákazník", business: "Firemní zákazník", name: "Celé jméno", company: "Firma", vatId: "DIČ (volitelné)", email: "E-mail", phone: "Telefon", street: "Ulice", number: "Číslo domu", address2: "Doplnění adresy (volitelné)", postcode: "PSČ", city: "Město / Region", country: "Země", address: "Dodací adresa", unloading: "Vykládka", site: "Přístup a usazení", curbside: "K obrubníku / vlastní vykládka", curbsideText: "Vhodné vybavení pro vykládku zajistíte na místě.", crane: "Vykládka jeřábem", craneText: "Prověříme vozidlo, přístup a bezpečné usazení.", date: "Preferované datum (volitelné)", access: "Přístup a místo usazení", accessPlaceholder: "Šířka, překážky, povrch a kontakt …", order: "Vaše objednávka", net: "Netto", vat: "DPH (19 %)", gross: "Zboží vč. DPH", taxPending: "Konečná daň bude ověřena.", shipping: "Doprava", shippingPending: "Ověříme podle PSČ, vykládky, počtu, velikostí a přístupu.", totalPending: "Konečná cena po kontrole dopravy", bulk: "U více kontejnerů posoudíme společnou dopravu a cenu.", invoice: "Faktura k potvrzení", invoiceText: "Před platbou obdržíte a potvrdíte konečnou částku.", sepa: "SEPA platební výzva", sepaText: "Po potvrzení obdržíte fakturu a SEPA údaje.", terms: "Souhlasím s", privacy: "Přečetl/a jsem zásady soukromí.", submit: "Odeslat objednávku ke kontrole", submitting: "Odesílání …", empty: "Košík je prázdný.", shop: "Vybrat kontejnery", success: "Objednávka přijata", successText: "Prověříme dostupnost, daň a dopravu a poté zašleme potvrzenou cenu.", error: "Objednávku se nepodařilo odeslat.", reference: "Reference", euVat: "DPH (předběžně 0 %)", euVatNote: "B2B dodání v EU: 0 % až po ověření DIČ a dopravy.", euTotal: "Předběžná cena zboží" },
  es: { title: "Pago", intro: "Pida directamente. Entrega e impuestos se revisan antes del pago.", step1: "1. Contacto y factura", step2: "2. Entrega y descarga", step3: "3. Revisión y pago", private: "Particular", business: "Empresa", name: "Nombre completo", company: "Empresa", vatId: "NIF-IVA (opcional)", email: "Correo", phone: "Teléfono", street: "Calle", number: "Número", address2: "Dirección línea 2 (opcional)", postcode: "Código postal", city: "Ciudad / Región", country: "País", address: "Dirección de entrega", unloading: "Descarga", site: "Acceso y colocación", curbside: "Acera / descarga propia", curbsideText: "Usted organiza el equipo de descarga.", crane: "Descarga con grúa", craneText: "Revisamos camión, acceso y colocación segura.", date: "Fecha preferida (opcional)", access: "Acceso y lugar de colocación", accessPlaceholder: "Anchura, obstáculos, superficie y contacto …", order: "Su pedido", net: "Neto", vat: "IVA (19%)", gross: "Mercancía IVA incluido", taxPending: "Se revisará el impuesto definitivo.", shipping: "Entrega", shippingPending: "Se revisa según código postal, descarga, cantidad, tamaños y acceso.", totalPending: "Total final tras revisar entrega", bulk: "Para varios contenedores revisamos transporte agrupado y precio.", invoice: "Factura para confirmar", invoiceText: "Recibe el importe final y confirma antes del pago.", sepa: "Solicitud de pago SEPA", sepaText: "Recibe factura y datos SEPA después de la confirmación.", terms: "Acepto los", privacy: "He leído la política de privacidad.", submit: "Enviar pedido para revisión", submitting: "Enviando …", empty: "El carrito está vacío.", shop: "Elegir contenedores", success: "Pedido recibido", successText: "Revisaremos disponibilidad, impuestos y entrega y enviaremos el total confirmado.", error: "No se pudo enviar el pedido.", reference: "Referencia", euVat: "IVA (0% provisional)", euVatNote: "Entrega B2B intracomunitaria: 0% tras verificar NIF-IVA y transporte.", euTotal: "Total provisional de mercancía" },
};

export function CheckoutPage({ locale }: { locale: Locale }) {
  const copy = copies[locale];
  const cartRaw = useSyncExternalStore(subscribeToCart, () => localStorage.getItem(CART_KEY) || "[]", () => "[]");
  const items = useMemo(() => parseItems(cartRaw), [cartRaw]);
  const [customerType, setCustomerType] = useState<"private" | "business">("private");
  const [countryCode, setCountryCode] = useState("DE");
  const [deliveryMethod, setDeliveryMethod] = useState("curbside");
  const [paymentMethod, setPaymentMethod] = useState("invoice");
  const [status, setStatus] = useState<"idle" | "sending" | "success" | "error">("idle");
  const [reference, setReference] = useState("");
  const countries = countryOptions(locale);
  const gross = items.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const net = gross / 1.19;
  const vat = gross - net;
  const germanTax = countryCode === "DE";
  const intraEuBusiness = customerType === "business" && !germanTax;
  const totalQuantity = items.reduce((sum, item) => sum + item.quantity, 0);
  const money = (value: number) => new Intl.NumberFormat(locale, { style: "currency", currency: "EUR" }).format(value);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus("sending");
    const form = new FormData(event.currentTarget);
    const payload = { locale, customerType, company: String(form.get("company") || ""), vatNumber: String(form.get("vatNumber") || ""), name: String(form.get("name") || ""), email: String(form.get("email") || ""), phone: String(form.get("phone") || ""), street: String(form.get("street") || ""), houseNumber: String(form.get("houseNumber") || ""), addressLine2: String(form.get("addressLine2") || ""), postcode: String(form.get("postcode") || ""), city: String(form.get("city") || ""), countryCode, deliveryMethod, accessNotes: String(form.get("accessNotes") || ""), preferredDate: String(form.get("preferredDate") || ""), paymentMethod, items: items.map(({ id, sku, quantity }) => ({ id, sku, quantity })), website: String(form.get("website") || ""), termsAccepted: form.get("terms") === "on", privacyAccepted: form.get("privacy") === "on" };
    try {
      const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json() as { reference?: string };
      if (!response.ok) throw new Error("Order failed");
      setReference(result.reference || ""); writeCart([]); setStatus("success");
    } catch { setStatus("error"); }
  }

  if (status === "success") return <main className="section-space min-h-[65vh] bg-zinc-100"><div className="container-shell max-w-3xl"><div className="surface-card p-8 text-center sm:p-12"><CheckCircle2 className="mx-auto h-14 w-14 text-green-700" /><h1 className="mt-5 text-3xl font-extrabold">{copy.success}</h1><p className="mx-auto mt-4 max-w-xl leading-7 text-zinc-600">{copy.successText}</p>{reference && <p className="mt-5 font-bold">{copy.reference}: {reference}</p>}<Link href={href(locale, "shop")} className="button-primary mt-8">{copy.shop}</Link></div></div></main>;
  if (items.length === 0) return <main className="section-space min-h-[65vh] bg-zinc-100"><div className="container-shell max-w-3xl"><div className="surface-card p-10 text-center"><PackageCheck className="mx-auto h-12 w-12 text-primary" /><h1 className="mt-5 text-2xl font-extrabold">{copy.empty}</h1><Link className="button-primary mt-6" href={href(locale, "shop")}>{copy.shop}</Link></div></div></main>;

  const field = "h-12 w-full border border-zinc-300 bg-white px-3 outline-none focus:border-primary";
  return <main className="section-space bg-zinc-100"><div className="container-shell"><div className="max-w-3xl"><p className="eyebrow">NORDIKA Container</p><h1 className="section-title mt-3">{copy.title}</h1><p className="section-intro">{copy.intro}</p></div>
    <form onSubmit={submit} className="mt-10 grid items-start gap-8 xl:grid-cols-[1fr_390px]">
      <div className="grid gap-6">
        <section className="surface-card p-6 sm:p-8"><h2 className="flex items-center gap-3 text-2xl font-extrabold"><Building2 className="h-6 w-6 text-primary" />{copy.step1}</h2><div className="mt-6 grid grid-cols-2 gap-2">{(["private", "business"] as const).map((value) => <label key={value} className={`cursor-pointer border p-3 text-center text-sm font-bold ${customerType === value ? "border-primary bg-blue-50 text-primary" : "border-zinc-300"}`}><input type="radio" value={value} checked={customerType === value} onChange={() => setCustomerType(value)} className="sr-only" />{value === "private" ? copy.private : copy.business}</label>)}</div><div className="mt-6 grid gap-5 sm:grid-cols-2">{customerType === "business" && <><Field label={copy.company} span><input className={field} name="company" required /></Field><Field label={intraEuBusiness ? copy.euVat : copy.vatId} span><input className={field} name="vatNumber" required={intraEuBusiness} /></Field></>}<Field label={copy.name} span><input className={field} name="name" required /></Field><Field label={copy.email}><input className={field} name="email" type="email" required /></Field><Field label={copy.phone}><input className={field} name="phone" type="tel" required /></Field></div></section>
        <section className="surface-card p-6 sm:p-8"><h2 className="flex items-center gap-3 text-2xl font-extrabold"><MapPin className="h-6 w-6 text-primary" />{copy.step2}</h2><h3 className="mt-7 border-b border-zinc-200 pb-2 text-sm font-extrabold uppercase tracking-wider text-primary">{copy.address}</h3><div className="mt-5 grid gap-5"><div className="grid gap-5 sm:grid-cols-[1fr_150px]"><Field label={copy.street}><input className={field} name="street" autoComplete="address-line1" required /></Field><Field label={copy.number}><input className={field} name="houseNumber" required /></Field></div><Field label={copy.address2}><input className={field} name="addressLine2" autoComplete="address-line2" /></Field><div className="grid gap-5 sm:grid-cols-[150px_1fr]"><Field label={copy.postcode}><input className={field} name="postcode" autoComplete="postal-code" required /></Field><Field label={copy.city}><input className={field} name="city" autoComplete="address-level2" required /></Field></div><Field label={copy.country}><select className={field} value={countryCode} onChange={(event) => setCountryCode(event.target.value)}>{countries.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></Field></div><h3 className="mt-8 border-b border-zinc-200 pb-2 text-sm font-extrabold uppercase tracking-wider text-primary">{copy.unloading}</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{[["curbside", copy.curbside, copy.curbsideText], ["crane", copy.crane, copy.craneText]].map(([value, title, text]) => <label key={value} className={`cursor-pointer border p-5 ${deliveryMethod === value ? "border-primary bg-blue-50" : "border-zinc-300"}`}><input type="radio" value={value} checked={deliveryMethod === value} onChange={() => setDeliveryMethod(value)} className="sr-only" /><strong className="block">{title}</strong><span className="mt-2 block text-sm leading-6 text-zinc-600">{text}</span></label>)}</div><h3 className="mt-8 border-b border-zinc-200 pb-2 text-sm font-extrabold uppercase tracking-wider text-primary">{copy.site}</h3><div className="mt-5 grid gap-5"><Field label={copy.date}><input className={field} name="preferredDate" type="date" /></Field><Field label={copy.access}><textarea name="accessNotes" required placeholder={copy.accessPlaceholder} className="min-h-32 w-full border border-zinc-300 bg-white p-3 outline-none focus:border-primary" /></Field></div></section>
        <section className="surface-card p-6 sm:p-8"><h2 className="flex items-center gap-3 text-2xl font-extrabold"><CreditCard className="h-6 w-6 text-primary" />{copy.step3}</h2><div className="mt-6 grid gap-3">{[["invoice", copy.invoice, copy.invoiceText], ["sepa", copy.sepa, copy.sepaText]].map(([value, title, text]) => <label key={value} className={`cursor-pointer border p-5 ${paymentMethod === value ? "border-primary bg-blue-50" : "border-zinc-300"}`}><input type="radio" value={value} checked={paymentMethod === value} onChange={() => setPaymentMethod(value)} className="mr-3 accent-primary" /><strong>{title}</strong><span className="mt-2 block pl-7 text-sm leading-6 text-zinc-600">{text}</span></label>)}</div><label className="mt-6 flex gap-3 text-sm leading-6"><input type="checkbox" name="terms" required className="mt-1 h-5 w-5 accent-primary" /><span>{copy.terms} <Link className="font-bold text-primary underline" href={href(locale, "terms")}>AGB</Link></span></label><label className="mt-3 flex gap-3 text-sm leading-6"><input type="checkbox" name="privacy" required className="mt-1 h-5 w-5 accent-primary" /><span>{copy.privacy} <Link className="font-bold text-primary underline" href={href(locale, "privacy")}>Privacy</Link></span></label><input name="website" tabIndex={-1} autoComplete="off" className="hidden" /></section>
      </div>
      <aside className="surface-card p-6 xl:sticky xl:top-32"><h2 className="text-2xl font-extrabold">{copy.order}</h2><ul className="mt-5 grid gap-4 border-b border-zinc-200 pb-5">{items.map((item) => <li key={item.id} className="flex justify-between gap-4 text-sm"><span><strong className="block">{item.title}</strong><span className="text-zinc-500">{item.sku} × {item.quantity}</span></span><strong className="whitespace-nowrap">{money((intraEuBusiness ? item.price / 1.19 : item.price) * item.quantity)}</strong></li>)}</ul>{germanTax ? <dl className="mt-5 grid gap-3 text-sm"><div className="flex justify-between"><dt>{copy.net}</dt><dd>{money(net)}</dd></div><div className="flex justify-between"><dt>{copy.vat}</dt><dd>{money(vat)}</dd></div><div className="flex justify-between border-t border-zinc-200 pt-3"><dt>{copy.gross}</dt><dd className="font-extrabold">{money(gross)}</dd></div></dl> : intraEuBusiness ? <div className="mt-5"><dl className="grid gap-3 text-sm"><div className="flex justify-between"><dt>{copy.net}</dt><dd>{money(net)}</dd></div><div className="flex justify-between"><dt>{copy.euVat}</dt><dd>{money(0)}</dd></div><div className="flex justify-between border-t border-zinc-200 pt-3"><dt>{copy.euTotal}</dt><dd className="font-extrabold">{money(net)}</dd></div></dl><p className="mt-3 border-l-4 border-primary bg-blue-50 p-3 text-xs leading-5 text-zinc-700">{copy.euVatNote}</p></div> : <div className="mt-5"><div className="flex justify-between"><span>{copy.gross}</span><strong>{money(gross)}</strong></div><p className="mt-2 text-xs leading-5 text-zinc-500">{copy.taxPending}</p></div>}<div className="mt-5 border-y border-zinc-200 py-4"><div className="flex items-center gap-2 font-bold"><Truck className="h-5 w-5 text-primary" />{copy.shipping}</div><p className="mt-2 text-sm leading-6 text-zinc-600">{copy.shippingPending}</p></div><p className="mt-4 text-lg font-extrabold">{copy.totalPending}</p>{totalQuantity > 1 && <p className="mt-4 border-l-4 border-orange-400 bg-orange-50 p-3 text-sm leading-6">{copy.bulk}</p>}{status === "error" && <p role="alert" className="mt-5 bg-red-50 p-3 text-sm font-bold text-red-800">{copy.error}</p>}<button disabled={status === "sending"} className="button-primary mt-6 w-full disabled:cursor-wait disabled:opacity-60">{status === "sending" ? copy.submitting : copy.submit}</button></aside>
    </form>
  </div></main>;
}

function Field({ label, children, span = false }: { label: string; children: React.ReactNode; span?: boolean }) { return <label className={`grid gap-2 text-sm font-bold ${span ? "sm:col-span-2" : ""}`}>{label}{children}</label>; }
function subscribeToCart(callback: () => void) { window.addEventListener(CART_EVENT, callback); window.addEventListener("storage", callback); return () => { window.removeEventListener(CART_EVENT, callback); window.removeEventListener("storage", callback); }; }
function parseItems(raw: string): CartItem[] { try { const parsed: unknown = JSON.parse(raw); return Array.isArray(parsed) ? parsed as CartItem[] : readCart(); } catch { return []; } }
