import Link from "next/link";
import { ArrowRight, Mail, MapPin, Phone } from "lucide-react";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { ContactForm } from "@/components/contact-form";
import { PageHero } from "@/components/page-hero";
import type { PageContent } from "@/lib/content";
import type { Locale } from "@/lib/i18n";
import { href, type RouteKey } from "@/lib/routes";
import { SITE } from "@/lib/site";

const contactCopy: Record<Locale, { depots: string; eyebrow: string; title: string; intro: string; topics: Array<{ title: string; text: string; key: RouteKey }> }> = {
  de: { depots: "Depots", eyebrow: "Schnell zum richtigen Thema", title: "Wobei können wir Sie unterstützen?", intro: "Wählen Sie den passenden Einstieg oder senden Sie uns Artikelnummer, Lieferort und eine kurze Beschreibung Ihres Projekts.", topics: [{ title: "Produkt & Angebot", text: "Bestand, Zustand, Ausstattung und Preis projektbezogen anfragen.", key: "quote" }, { title: "Lieferung & Aufstellung", text: "Zufahrt, Untergrund, Entladung und möglichen Termin klären.", key: "delivery" }, { title: "Containerumbau", text: "Öffnungen, Elektrik, Dämmung oder Innenausbau besprechen.", key: "conversions" }, { title: "Reklamation", text: "Auftrag zuordnen und Abweichungen mit Fotos dokumentieren.", key: "complaints" }, { title: "Rückgabe", text: "Ablauf und Schwerlast-Rücktransport vorab abstimmen.", key: "returns" }, { title: "Unternehmensangaben", text: "Anbieter- und rechtliche Kontaktinformationen einsehen.", key: "imprint" }] },
  en: { depots: "Depots", eyebrow: "Find the right route", title: "How can we support you?", intro: "Choose the relevant topic or send us the item number, delivery location and a short project description.", topics: [{ title: "Product & quote", text: "Ask about stock, condition, equipment and project pricing.", key: "quote" }, { title: "Delivery & installation", text: "Clarify access, ground, unloading and possible timing.", key: "delivery" }, { title: "Container conversion", text: "Discuss openings, electrics, insulation or interior fit-out.", key: "conversions" }, { title: "Complaint", text: "Identify the order and document discrepancies with photos.", key: "complaints" }, { title: "Return", text: "Agree the process and heavy-haul return before transport.", key: "returns" }, { title: "Company details", text: "View provider and legal contact information.", key: "imprint" }] },
  nl: { depots: "Depots", eyebrow: "Snel naar het juiste onderwerp", title: "Waarmee kunnen we helpen?", intro: "Kies het onderwerp of stuur artikelnummer, afleverplaats en een korte projectomschrijving.", topics: [{ title: "Product & offerte", text: "Vraag naar voorraad, staat, uitrusting en projectprijs.", key: "quote" }, { title: "Levering & plaatsing", text: "Stem toegang, ondergrond, lossing en planning af.", key: "delivery" }, { title: "Containerombouw", text: "Bespreek openingen, elektra, isolatie of interieur.", key: "conversions" }, { title: "Klacht", text: "Koppel de order en leg afwijkingen met foto's vast.", key: "complaints" }, { title: "Retour", text: "Stem proces en zwaar retourtransport vooraf af.", key: "returns" }, { title: "Bedrijfsgegevens", text: "Bekijk aanbieder en juridische contactinformatie.", key: "imprint" }] },
  it: { depots: "Depositi", eyebrow: "Trova il percorso giusto", title: "Come possiamo aiutarti?", intro: "Scegli l'argomento oppure invia codice articolo, luogo di consegna e breve descrizione del progetto.", topics: [{ title: "Prodotto e preventivo", text: "Chiedi stock, condizioni, dotazione e prezzo del progetto.", key: "quote" }, { title: "Consegna e posa", text: "Verifica accesso, terreno, scarico e possibile data.", key: "delivery" }, { title: "Trasformazione", text: "Parla di aperture, impianto elettrico, isolamento o interni.", key: "conversions" }, { title: "Reclamo", text: "Identifica l'ordine e documenta le difformità con foto.", key: "complaints" }, { title: "Reso", text: "Concorda procedura e trasporto pesante prima del rientro.", key: "returns" }, { title: "Dati aziendali", text: "Consulta fornitore e contatti legali.", key: "imprint" }] },
  cs: { depots: "Depa", eyebrow: "Rychle ke správnému tématu", title: "S čím vám pomůžeme?", intro: "Zvolte téma nebo pošlete číslo produktu, místo dodání a stručný popis projektu.", topics: [{ title: "Produkt a nabídka", text: "Ověřte sklad, stav, výbavu a cenu projektu.", key: "quote" }, { title: "Doprava a usazení", text: "Projednejte příjezd, podklad, vykládku a termín.", key: "delivery" }, { title: "Úprava kontejneru", text: "Proberte otvory, elektroinstalaci, izolaci nebo interiér.", key: "conversions" }, { title: "Reklamace", text: "Přiřaďte objednávku a zdokumentujte nesrovnalosti.", key: "complaints" }, { title: "Vrácení", text: "Předem dohodněte postup a těžkou zpětnou dopravu.", key: "returns" }, { title: "Údaje společnosti", text: "Zobrazte poskytovatele a právní kontakty.", key: "imprint" }] },
  es: { depots: "Depósitos", eyebrow: "Llega al tema adecuado", title: "¿Cómo podemos ayudarte?", intro: "Elige el tema o envía número de artículo, lugar de entrega y breve descripción del proyecto.", topics: [{ title: "Producto y presupuesto", text: "Consulta stock, estado, equipamiento y precio del proyecto.", key: "quote" }, { title: "Entrega e instalación", text: "Aclara acceso, suelo, descarga y posible fecha.", key: "delivery" }, { title: "Transformación", text: "Habla de aperturas, electricidad, aislamiento o interior.", key: "conversions" }, { title: "Reclamación", text: "Identifica el pedido y documenta diferencias con fotos.", key: "complaints" }, { title: "Devolución", text: "Acuerda proceso y transporte pesado antes del retorno.", key: "returns" }, { title: "Datos de empresa", text: "Consulta proveedor e información legal de contacto.", key: "imprint" }] },
};

export function ContactPage({ locale, content }: { locale: Locale; content: PageContent }) {
  const copy = contactCopy[locale];
  return <main><Breadcrumbs locale={locale} items={[{ label: content.title }]} /><PageHero eyebrow={content.eyebrow} title={content.title} intro={content.intro} /><section className="section-space bg-zinc-100"><div className="container-shell grid gap-8 lg:grid-cols-[1fr_1.4fr]"><div className="surface-card h-fit p-7 sm:p-8"><h2 className="text-2xl font-extrabold">{SITE.legalName}</h2><div className="mt-6 grid gap-4 text-sm"><a className="flex items-center gap-3 hover:text-primary" href={`tel:${SITE.phoneHref}`}><Phone className="h-5 w-5 text-primary" />{SITE.phone}</a><a className="flex items-center gap-3 hover:text-primary" href={`mailto:${SITE.email}`}><Mail className="h-5 w-5 text-primary" />{SITE.email}</a><p className="flex items-start gap-3"><MapPin className="mt-0.5 h-5 w-5 shrink-0 text-primary" />{SITE.address.street}<br />{SITE.address.postalCode} {SITE.address.city}</p></div></div><ContactForm locale={locale} /></div></section><section className="section-space bg-white"><div className="container-shell"><p className="eyebrow">{copy.eyebrow}</p><h2 className="section-title">{copy.title}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-zinc-600">{copy.intro}</p><div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{copy.topics.map((topic) => <Link key={topic.key} href={href(locale, topic.key)} className="group surface-card p-6"><h3 className="text-xl font-extrabold">{topic.title}</h3><p className="mt-3 leading-7 text-zinc-600">{topic.text}</p><span className="mt-5 inline-flex items-center gap-2 font-extrabold text-primary"><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section></main>;
}
