import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { PageHero } from "@/components/page-hero";
import type { Locale } from "@/lib/i18n";
import { href, type RouteKey } from "@/lib/routes";
import { SITE } from "@/lib/site";

type LegalKey = "imprint" | "privacy" | "terms" | "withdrawal" | "withdrawalForm" | "returns" | "payments" | "cookies" | "complaints" | "warranty" | "accessibility";
type LegalSection = { title: string; paragraphs: string[]; bullets?: string[] };
type LegalCopy = { eyebrow: string; title: string; intro: string; sections: LegalSection[]; related: LegalKey[] };
type PolicyKey = Exclude<LegalKey, "imprint">;

const titles: Record<Locale, Record<LegalKey, string>> = {
  de: { imprint: "Impressum", privacy: "Datenschutzerklärung", terms: "Allgemeine Geschäftsbedingungen", withdrawal: "Widerrufsrecht", withdrawalForm: "Muster-Widerrufsformular", returns: "Rückgabe und Erstattung", payments: "Zahlungsarten", cookies: "Cookie-Richtlinie", complaints: "Reklamation und Beschwerde", warranty: "Gewährleistung und Mängel", accessibility: "Barrierefreiheit" },
  en: { imprint: "Legal notice", privacy: "Privacy policy", terms: "Terms and conditions", withdrawal: "Right of withdrawal", withdrawalForm: "Model withdrawal form", returns: "Returns and refunds", payments: "Payment methods", cookies: "Cookie policy", complaints: "Complaints", warranty: "Warranty and defects", accessibility: "Accessibility" },
  nl: { imprint: "Colofon", privacy: "Privacyverklaring", terms: "Algemene voorwaarden", withdrawal: "Herroepingsrecht", withdrawalForm: "Modelformulier voor herroeping", returns: "Retouren en terugbetaling", payments: "Betaalmethoden", cookies: "Cookiebeleid", complaints: "Klachten", warranty: "Garantie en gebreken", accessibility: "Toegankelijkheid" },
  it: { imprint: "Note legali", privacy: "Informativa sulla privacy", terms: "Termini e condizioni", withdrawal: "Diritto di recesso", withdrawalForm: "Modulo tipo di recesso", returns: "Resi e rimborsi", payments: "Metodi di pagamento", cookies: "Cookie policy", complaints: "Reclami", warranty: "Garanzia e difetti", accessibility: "Accessibilità" },
  cs: { imprint: "Právní informace", privacy: "Ochrana soukromí", terms: "Obchodní podmínky", withdrawal: "Odstoupení od smlouvy", withdrawalForm: "Vzorový formulář pro odstoupení", returns: "Vrácení a refundace", payments: "Platební metody", cookies: "Zásady cookies", complaints: "Reklamace a stížnosti", warranty: "Záruka a vady", accessibility: "Přístupnost" },
  es: { imprint: "Aviso legal", privacy: "Política de privacidad", terms: "Términos y condiciones", withdrawal: "Derecho de desistimiento", withdrawalForm: "Formulario modelo de desistimiento", returns: "Devoluciones y reembolsos", payments: "Métodos de pago", cookies: "Política de cookies", complaints: "Reclamaciones", warranty: "Garantía y defectos", accessibility: "Accesibilidad" },
};

const ui: Record<Locale, { eyebrow: string; intro: string; provider: string; contact: string; coverage: string; related: string; contract: string }> = {
  de: { eyebrow: "Service und Recht", intro: "Transparente Informationen zu Anbieter, Datenverarbeitung und Vertragsabwicklung bei NORDIKA Container.", provider: "Anbieter", contact: "Kontakt und verbindliche Unterlagen", coverage: "Was diese Information abdeckt", related: "Weitere Informationen", contract: "Die verbindlichen Angaben im konkreten Angebot, in der Auftragsbestätigung und in den vor Vertragsschluss bereitgestellten Unterlagen gehen dieser allgemeinen Übersicht vor." },
  en: { eyebrow: "Service and legal", intro: "Clear information about the provider, data processing and contract handling at NORDIKA Container.", provider: "Provider", contact: "Contact and binding documents", coverage: "What this information covers", related: "Related information", contract: "The binding information in the specific offer, order confirmation and documents supplied before the contract takes precedence over this general overview." },
  nl: { eyebrow: "Service en juridisch", intro: "Duidelijke informatie over de aanbieder, gegevensverwerking en contractafhandeling bij NORDIKA Container.", provider: "Aanbieder", contact: "Contact en bindende documenten", coverage: "Wat deze informatie omvat", related: "Meer informatie", contract: "De bindende informatie in de concrete offerte, orderbevestiging en vóór de overeenkomst verstrekte documenten gaat voor op dit algemene overzicht." },
  it: { eyebrow: "Servizio e aspetti legali", intro: "Informazioni chiare sul fornitore, il trattamento dei dati e la gestione dei contratti di NORDIKA Container.", provider: "Fornitore", contact: "Contatti e documenti vincolanti", coverage: "Cosa comprende questa informazione", related: "Altre informazioni", contract: "Prevalgono le informazioni vincolanti contenute nell'offerta specifica, nella conferma d'ordine e nei documenti forniti prima del contratto." },
  cs: { eyebrow: "Servis a právní informace", intro: "Jasné informace o poskytovateli, zpracování údajů a smluvním procesu společnosti NORDIKA Container.", provider: "Poskytovatel", contact: "Kontakt a závazné dokumenty", coverage: "Co tato informace zahrnuje", related: "Související informace", contract: "Závazné údaje v konkrétní nabídce, potvrzení objednávky a dokumentech poskytnutých před smlouvou mají přednost před tímto přehledem." },
  es: { eyebrow: "Servicio e información legal", intro: "Información clara sobre el proveedor, el tratamiento de datos y la gestión contractual de NORDIKA Container.", provider: "Proveedor", contact: "Contacto y documentos vinculantes", coverage: "Qué cubre esta información", related: "Información relacionada", contract: "Prevalece la información vinculante de la oferta concreta, la confirmación de pedido y los documentos facilitados antes del contrato." },
};

const registerTitle: Record<Locale, string> = { de: "Registerangaben", en: "Register details", nl: "Registergegevens", it: "Dati del registro", cs: "Registrační údaje", es: "Datos registrales" };

const summaries: Record<Locale, Record<PolicyKey, string>> = {
  de: {
    privacy: "Wir verarbeiten personenbezogene Daten nur, soweit dies für den sicheren Websitebetrieb, die Bearbeitung von Anfragen oder die Vertragsabwicklung erforderlich ist. Ihre gesetzlichen Datenschutzrechte bleiben gewahrt.",
    terms: "Diese Bedingungen erläutern den Vertragsschluss für Verbraucher und Unternehmer, individuelle Transportkosten, Lieferung von Schwerlastgütern, gebrauchte Container, Zahlung und gesetzliche Mängelrechte.",
    withdrawal: "Verbraucher haben bei anwendbaren Fernabsatzverträgen grundsätzlich ein gesetzliches Widerrufsrecht von 14 Tagen. Für eindeutig kundenspezifisch hergestellte Waren können gesetzliche Ausnahmen gelten.",
    withdrawalForm: "Mit diesem Muster können Verbraucher einen anwendbaren Widerruf eindeutig erklären. Das Formular ist freiwillig; eine andere eindeutige Erklärung ist ebenfalls möglich.",
    returns: "Container sind mehrere Tonnen schwere Industriegüter. Rückgabe, Abholung und grenzüberschreitender Rücktransport müssen deshalb immer mit NORDIKA Container koordiniert werden; gesetzliche Verbraucher- und Mängelrechte bleiben unberührt.",
    payments: "Zahlungsart, Gesamtpreis, individuelle Transportkosten, Bankverbindung und Fälligkeit werden vor Vertragsschluss im Angebot beziehungsweise in der Auftragsbestätigung transparent ausgewiesen.",
    cookies: "Die Website verwendet technisch notwendige Speicherungen für Kernfunktionen. Optionale Technologien dürfen nur im Rahmen der anwendbaren Einwilligungsregeln eingesetzt werden.",
    complaints: "Melden Sie Abweichungen oder Schäden möglichst früh mit Artikel- oder Auftragsnummer, Beschreibung und aussagekräftigen Fotos. Wir prüfen den konkreten Vorgang und stimmen die nächsten Schritte ab.",
    warranty: "Produktzustand, vereinbarte Beschaffenheit und Verwendungszweck sind voneinander zu unterscheiden. Gesetzliche Mängelrechte und die konkrete Vertragsvereinbarung bestimmen den Anspruch.",
    accessibility: "Wir möchten unsere Website und unsere Kommunikation für möglichst viele Menschen verständlich und nutzbar machen und verbessern Barrieren fortlaufend.",
  },
  en: {
    privacy: "We process personal data only where necessary for secure site operation, enquiries or contract performance. Your statutory data-protection rights remain available.", terms: "Offers, prices, availability, delivery, transfer of risk, warranty and payment are confirmed in the specific contract document. Mandatory consumer rights remain unaffected.", withdrawal: "Consumers may have a statutory right of withdrawal for distance contracts. Exceptions may apply in particular to custom-made or personalised conversions.", withdrawalForm: "Consumers can use this model to make an applicable withdrawal clear. Using the form is optional; another unambiguous statement is also possible.", returns: "Please agree returns with us before transport. Statutory warranty and consumer rights remain unaffected; the process and costs depend on the contract and reason for return.", payments: "The payment method, bank details and due date appear only in the binding offer, order confirmation or invoice.", cookies: "The site uses technically necessary storage for core functions. Optional technologies may be used only in accordance with applicable consent rules.", complaints: "Report discrepancies or damage as early as possible with the product or order number, a description and useful photos. We review the individual case and agree the next steps.", warranty: "Product condition, agreed characteristics and intended use are separate questions. Statutory defect rights and the specific contract determine any claim.", accessibility: "We want our website and communication to be understandable and usable by as many people as possible and work continuously to reduce barriers.",
  },
  nl: {
    privacy: "We verwerken persoonsgegevens alleen voor een veilige website, vragen of uitvoering van de overeenkomst. Uw wettelijke privacyrechten blijven bestaan.", terms: "Offertes, prijzen, beschikbaarheid, levering, risico, garantie en betaling worden in het concrete contractdocument bevestigd. Dwingende consumentenrechten blijven gelden.", withdrawal: "Consumenten kunnen bij overeenkomsten op afstand een wettelijk herroepingsrecht hebben. Uitzonderingen kunnen vooral gelden voor maatwerk of gepersonaliseerde ombouw.", withdrawalForm: "Met dit model kan een consument een toepasselijke herroeping duidelijk verklaren. Het formulier is niet verplicht; een andere ondubbelzinnige verklaring kan ook.", returns: "Stem retouren vóór het transport met ons af. Wettelijke garantie- en consumentenrechten blijven gelden; proces en kosten hangen af van contract en retourreden.", payments: "Betaalwijze, bankgegevens en vervaldatum staan alleen in de bindende offerte, orderbevestiging of factuur.", cookies: "De website gebruikt technisch noodzakelijke opslag voor kernfuncties. Optionele technologie mag alleen volgens de geldende toestemmingsregels worden gebruikt.", complaints: "Meld afwijkingen of schade zo vroeg mogelijk met product- of ordernummer, omschrijving en duidelijke foto's. We beoordelen de situatie en stemmen vervolgstappen af.", warranty: "Productconditie, overeengekomen eigenschappen en gebruiksdoel zijn verschillende zaken. Wettelijke rechten bij gebreken en het contract bepalen de aanspraak.", accessibility: "We willen onze website en communicatie voor zoveel mogelijk mensen begrijpelijk en bruikbaar maken en verminderen barrières voortdurend.",
  },
  it: {
    privacy: "Trattiamo i dati personali solo per la sicurezza del sito, le richieste o l'esecuzione del contratto. Restano disponibili i diritti previsti dalla legge.", terms: "Offerte, prezzi, disponibilità, consegna, rischio, garanzia e pagamento sono confermati nel documento contrattuale specifico. Restano validi i diritti obbligatori dei consumatori.", withdrawal: "I consumatori possono avere un diritto legale di recesso nei contratti a distanza. Possono esserci eccezioni soprattutto per trasformazioni su misura o personalizzate.", withdrawalForm: "Il consumatore può usare questo modello per dichiarare chiaramente un recesso applicabile. Il modulo è facoltativo; è valida anche un'altra dichiarazione inequivocabile.", returns: "Concorda il reso con noi prima del trasporto. Restano invariati i diritti legali di garanzia e consumo; procedura e costi dipendono dal contratto e dal motivo.", payments: "Metodo, coordinate bancarie e scadenza compaiono solo nell'offerta vincolante, conferma d'ordine o fattura.", cookies: "Il sito usa memorizzazioni tecnicamente necessarie per le funzioni essenziali. Le tecnologie opzionali possono essere usate solo secondo le regole sul consenso.", complaints: "Segnala difformità o danni al più presto con codice prodotto o ordine, descrizione e foto utili. Esaminiamo il caso e concordiamo i passaggi successivi.", warranty: "Condizione del prodotto, caratteristiche concordate e uso previsto sono aspetti distinti. I diritti legali per difetti e il contratto determinano la tutela.", accessibility: "Vogliamo rendere sito e comunicazioni comprensibili e utilizzabili dal maggior numero di persone e riduciamo continuamente le barriere.",
  },
  cs: {
    privacy: "Osobní údaje zpracováváme pouze pro bezpečný provoz webu, vyřízení poptávek nebo plnění smlouvy. Vaše zákonná práva na ochranu údajů zůstávají zachována.", terms: "Nabídky, ceny, dostupnost, doprava, přechod rizika, záruka a platba se potvrzují v konkrétním smluvním dokumentu. Povinná práva spotřebitele zůstávají zachována.", withdrawal: "Spotřebitelé mohou mít u smluv na dálku zákonné právo odstoupit. Výjimky se mohou týkat zejména zakázkových či personalizovaných úprav.", withdrawalForm: "Tento vzor může spotřebitel použít k jednoznačnému odstoupení. Formulář není povinný; lze použít i jiné jednoznačné prohlášení.", returns: "Vrácení s námi dohodněte před dopravou. Zákonná práva ze záruky a ochrany spotřebitele zůstávají zachována; postup a náklady závisí na smlouvě a důvodu.", payments: "Způsob platby, bankovní spojení a splatnost jsou uvedeny pouze v závazné nabídce, potvrzení objednávky nebo faktuře.", cookies: "Web používá technicky nezbytné ukládání pro základní funkce. Volitelné technologie lze použít jen podle platných pravidel souhlasu.", complaints: "Nesrovnalost či škodu oznamte co nejdříve s číslem produktu nebo objednávky, popisem a fotografiemi. Případ prověříme a dohodneme další postup.", warranty: "Stav produktu, sjednané vlastnosti a účel použití jsou odlišné otázky. Nárok určují zákonná práva z vad a konkrétní smlouva.", accessibility: "Chceme, aby web i komunikace byly srozumitelné a použitelné pro co nejvíce lidí, a průběžně odstraňujeme bariéry.",
  },
  es: {
    privacy: "Tratamos datos personales solo para la seguridad del sitio, las consultas o la ejecución del contrato. Se mantienen sus derechos legales de protección de datos.", terms: "Ofertas, precios, disponibilidad, entrega, transmisión del riesgo, garantía y pago se confirman en el documento contractual concreto. Se mantienen los derechos obligatorios del consumidor.", withdrawal: "Los consumidores pueden tener derecho legal de desistimiento en contratos a distancia. Puede haber excepciones, especialmente para transformaciones a medida o personalizadas.", withdrawalForm: "El consumidor puede usar este modelo para declarar claramente un desistimiento aplicable. El formulario es opcional; también sirve otra declaración inequívoca.", returns: "Acuerda la devolución con nosotros antes del transporte. Los derechos legales de garantía y consumo se mantienen; proceso y costes dependen del contrato y el motivo.", payments: "Método, cuenta bancaria y vencimiento aparecen únicamente en la oferta vinculante, confirmación de pedido o factura.", cookies: "El sitio utiliza almacenamiento técnicamente necesario para funciones esenciales. Las tecnologías opcionales solo pueden usarse conforme a las reglas de consentimiento.", complaints: "Comunica diferencias o daños cuanto antes con número de producto o pedido, descripción y fotos útiles. Revisamos el caso y acordamos los pasos siguientes.", warranty: "El estado del producto, las características acordadas y el uso previsto son cuestiones distintas. Los derechos legales por defectos y el contrato concreto determinan la reclamación.", accessibility: "Queremos que nuestro sitio y comunicación sean comprensibles y utilizables por el mayor número de personas y trabajamos continuamente para reducir barreras.",
  },
};

const actions: Record<Locale, Record<PolicyKey, string[]>> = {
  de: {
    privacy: ["Verarbeitungen: Serverbetrieb, Anfragen, Angebote, Bestellungen und Lieferung", "Rechte: Auskunft, Berichtigung, Löschung, Einschränkung und Widerspruch im gesetzlichen Rahmen", "Kontakt oder Beschwerde bei einer zuständigen Datenschutzaufsicht"],
    terms: ["Zustand, Ausstattung, Preis, Lieferort und Entladung werden im Angebot festgehalten", "Verfügbarkeit gilt erst mit verbindlicher Bestätigung", "Zufahrt, tragfähiger Untergrund und örtliche Genehmigungen sind vorab zu klären"],
    withdrawal: ["Eindeutige Erklärung mit Name, Anschrift und betroffenem Vertrag", "Bestell- oder Auftragsnummer und Datum angeben", "Rücktransport wegen Schwerlastlogistik immer vorher abstimmen"],
    withdrawalForm: ["Hiermit widerrufe(n) ich/wir den Vertrag über …", "Bestellt am / erhalten am …", "Name, Anschrift, Datum und bei Papierform Unterschrift"],
    returns: ["Container bei Übergabe prüfen und sichtbare Schäden sofort dokumentieren", "Artikelnummer, Beschreibung sowie Übersichts- und Detailfotos senden", "Abholung oder Rücktransport schriftlich koordinieren"],
    payments: ["Rechnung, Auftragsnummer und Verwendungszweck abgleichen", "Unerwartete Änderungen von Bankdaten über bekannte Kontaktdaten prüfen", "Zahlungsbeleg für Rückfragen aufbewahren"],
    cookies: ["Notwendige Speicherung kann Sprache, Warenkorb, Sicherheit und Formulare unterstützen", "Optionale Zwecke benötigen eine wirksame Rechtsgrundlage und gegebenenfalls Auswahl", "Browser-Speicher kann in den Geräteeinstellungen gelöscht werden"],
    complaints: ["Problem und Zeitpunkt beschreiben", "Artikel- oder Auftragsnummer, Lieferschein und Fotos beifügen", "Reparatur oder Rücktransport nicht ohne Abstimmung veranlassen"],
    warranty: ["Normale Gebrauchsspuren der vereinbarten Zustandsklasse sind nicht automatisch ein Mangel", "Zustand dokumentieren und unnötige Folgeschäden vermeiden", "Prüfung und mögliche Nacherfüllung ermöglichen"],
    accessibility: ["Betroffene Seite, Gerät oder Hilfsmittel und benötigte Information nennen", "Kontakt per E-Mail oder Telefon", "Wichtige Information kann nach Möglichkeit alternativ bereitgestellt werden"],
  },
  en: {
    privacy: ["Processing: secure site operation, enquiries, offers, orders and delivery", "Rights: access, correction, erasure, restriction and objection where the law provides", "Contact us or a competent data-protection authority"], terms: ["Condition, equipment, price, delivery site and unloading are recorded in the offer", "Availability becomes binding only when confirmed", "Access, load-bearing ground and local permits must be clarified"], withdrawal: ["Clear statement with name, address and affected contract", "Give the order or job number and date", "Always agree heavy-haul return transport in advance"], withdrawalForm: ["I/we hereby withdraw from the contract concerning …", "Ordered on / received on …", "Name, address, date and signature for a paper form"], returns: ["Inspect at handover and record visible damage immediately", "Send item number, description, overview and detail photos", "Coordinate collection or return transport in writing"], payments: ["Match invoice, order number and payment reference", "Verify unexpected bank-detail changes through established contacts", "Keep proof of payment"], cookies: ["Necessary storage can support language, basket, security and forms", "Optional purposes need a valid legal basis and, where required, a choice", "Browser storage can be cleared in device settings"], complaints: ["Describe the problem and when it occurred", "Attach product or order number, delivery note and photos", "Do not arrange repair or return transport without agreement"], warranty: ["Normal signs of use for the agreed grade are not automatically defects", "Document condition and prevent avoidable further damage", "Allow inspection and a possible remedy"], accessibility: ["Give the page, device or assistive technology and information required", "Contact us by email or telephone", "Important information can be provided in an alternative way where possible"],
  },
  nl: {
    privacy: ["Verwerking: veilige website, vragen, offertes, bestellingen en levering", "Rechten: inzage, correctie, verwijdering, beperking en bezwaar volgens de wet", "Neem contact op met ons of een bevoegde toezichthouder"], terms: ["Staat, uitrusting, prijs, afleverplaats en lossing staan in de offerte", "Beschikbaarheid is pas bindend na bevestiging", "Toegang, draagkrachtige ondergrond en lokale vergunningen moeten worden gecontroleerd"], withdrawal: ["Duidelijke verklaring met naam, adres en betreffende overeenkomst", "Bestel- of opdrachtnummer en datum vermelden", "Zwaar retourtransport altijd vooraf afstemmen"], withdrawalForm: ["Hierbij herroep(en) ik/wij de overeenkomst betreffende …", "Besteld op / ontvangen op …", "Naam, adres, datum en handtekening op papier"], returns: ["Bij levering controleren en zichtbare schade direct vastleggen", "Artikelnummer, omschrijving en overzichts- en detailfoto's sturen", "Ophalen of retourtransport schriftelijk afstemmen"], payments: ["Factuur, ordernummer en betalingskenmerk vergelijken", "Onverwachte wijziging van bankgegevens via bekende contacten verifiëren", "Betalingsbewijs bewaren"], cookies: ["Noodzakelijke opslag ondersteunt taal, winkelwagen, beveiliging en formulieren", "Optionele doelen vereisen een geldige grondslag en zo nodig keuze", "Browseropslag kan in apparaatinstellingen worden gewist"], complaints: ["Probleem en moment beschrijven", "Product- of ordernummer, afleverdocument en foto's meesturen", "Geen reparatie of retour zonder overleg"], warranty: ["Normale gebruikssporen voor de afgesproken klasse zijn niet automatisch gebreken", "Staat documenteren en verdere schade voorkomen", "Inspectie en mogelijk herstel toestaan"], accessibility: ["Pagina, apparaat of hulpmiddel en benodigde informatie noemen", "Contact per e-mail of telefoon", "Belangrijke informatie waar mogelijk alternatief ontvangen"],
  },
  it: {
    privacy: ["Trattamenti: sito sicuro, richieste, offerte, ordini e consegna", "Diritti: accesso, rettifica, cancellazione, limitazione e opposizione nei limiti di legge", "Contatta noi o l'autorità competente"], terms: ["Condizione, dotazione, prezzo, luogo e scarico sono indicati nell'offerta", "La disponibilità è vincolante solo dopo conferma", "Accesso, terreno portante e permessi locali vanno verificati"], withdrawal: ["Dichiarazione chiara con nome, indirizzo e contratto", "Indicare numero ordine o commessa e data", "Concordare sempre prima il trasporto pesante di ritorno"], withdrawalForm: ["Con la presente recedo/recediamo dal contratto relativo a …", "Ordinato il / ricevuto il …", "Nome, indirizzo, data e firma su carta"], returns: ["Controllare alla consegna e documentare subito i danni visibili", "Inviare codice, descrizione e foto generali e dettagliate", "Concordare per iscritto ritiro o trasporto di ritorno"], payments: ["Confrontare fattura, ordine e causale", "Verificare cambi inattesi del conto tramite i contatti noti", "Conservare la prova di pagamento"], cookies: ["La memoria necessaria supporta lingua, carrello, sicurezza e moduli", "Le finalità opzionali richiedono base valida e, se previsto, scelta", "La memoria del browser si elimina dalle impostazioni"], complaints: ["Descrivere problema e momento", "Allegare prodotto o ordine, documento di consegna e foto", "Non organizzare riparazione o reso senza accordo"], warranty: ["I normali segni d'uso della classe concordata non sono automaticamente difetti", "Documentare e prevenire ulteriori danni", "Consentire verifica e possibile rimedio"], accessibility: ["Indicare pagina, dispositivo o tecnologia assistiva e informazione richiesta", "Contatto via e-mail o telefono", "Informazioni importanti in forma alternativa ove possibile"],
  },
  cs: {
    privacy: ["Zpracování: bezpečný web, poptávky, nabídky, objednávky a doprava", "Práva: přístup, oprava, výmaz, omezení a námitka podle zákona", "Kontaktujte nás nebo příslušný dozorový úřad"], terms: ["Stav, výbava, cena, místo a vykládka jsou uvedeny v nabídce", "Dostupnost je závazná až po potvrzení", "Příjezd, únosný podklad a místní povolení je nutné ověřit"], withdrawal: ["Jasné prohlášení se jménem, adresou a smlouvou", "Uvést číslo objednávky či zakázky a datum", "Těžkou zpětnou dopravu vždy předem dohodnout"], withdrawalForm: ["Tímto odstupuji/odstupujeme od smlouvy týkající se …", "Objednáno / převzato dne …", "Jméno, adresa, datum a podpis u papírové formy"], returns: ["Při předání zkontrolovat a viditelné škody ihned zdokumentovat", "Zaslat číslo, popis a celkové i detailní fotografie", "Písemně dohodnout odvoz nebo vrácení"], payments: ["Porovnat fakturu, objednávku a platební údaj", "Nečekanou změnu účtu ověřit známými kontakty", "Uschovat doklad o platbě"], cookies: ["Nezbytné ukládání podporuje jazyk, košík, bezpečnost a formuláře", "Volitelné účely vyžadují platný základ a případně volbu", "Úložiště prohlížeče lze smazat v nastavení"], complaints: ["Popsat problém a okamžik zjištění", "Přiložit produkt či objednávku, dodací list a fotografie", "Bez dohody nezařizovat opravu ani vrácení"], warranty: ["Běžné stopy používání pro sjednanou třídu nejsou automaticky vadou", "Stav zdokumentovat a zabránit dalším škodám", "Umožnit kontrolu a případnou nápravu"], accessibility: ["Uvést stránku, zařízení či pomůcku a potřebnou informaci", "Kontakt e-mailem nebo telefonem", "Důležité informace lze podle možnosti poskytnout jinak"],
  },
  es: {
    privacy: ["Tratamientos: sitio seguro, consultas, ofertas, pedidos y entrega", "Derechos: acceso, rectificación, supresión, limitación y oposición conforme a la ley", "Contacta con nosotros o una autoridad competente"], terms: ["Estado, equipamiento, precio, lugar y descarga constan en la oferta", "La disponibilidad solo es vinculante tras confirmación", "Acceso, suelo portante y permisos locales deben comprobarse"], withdrawal: ["Declaración clara con nombre, dirección y contrato", "Indicar número de pedido o trabajo y fecha", "Acordar siempre antes el transporte pesado de retorno"], withdrawalForm: ["Por la presente desisto/desistimos del contrato relativo a …", "Pedido el / recibido el …", "Nombre, dirección, fecha y firma en papel"], returns: ["Revisar en la entrega y documentar de inmediato daños visibles", "Enviar número, descripción y fotos generales y de detalle", "Coordinar por escrito recogida o transporte de retorno"], payments: ["Comparar factura, pedido y referencia de pago", "Verificar cambios inesperados de cuenta por contactos conocidos", "Guardar justificante"], cookies: ["El almacenamiento necesario apoya idioma, cesta, seguridad y formularios", "Los fines opcionales requieren base válida y, cuando proceda, elección", "El almacenamiento se borra en los ajustes del navegador"], complaints: ["Describir problema y momento", "Adjuntar producto o pedido, albarán y fotos", "No organizar reparación ni retorno sin acuerdo"], warranty: ["Las marcas normales del grado acordado no son automáticamente defectos", "Documentar y evitar daños adicionales", "Permitir inspección y posible solución"], accessibility: ["Indicar página, dispositivo o tecnología de apoyo e información requerida", "Contacto por correo o teléfono", "Información importante en formato alternativo cuando sea posible"],
  },
};

const related: Record<LegalKey, LegalKey[]> = {
  imprint: ["privacy", "terms", "accessibility"], privacy: ["cookies", "accessibility", "imprint"], terms: ["payments", "returns", "warranty"], withdrawal: ["withdrawalForm", "returns", "terms"], withdrawalForm: ["withdrawal", "returns", "imprint"], returns: ["complaints", "warranty", "withdrawal"], payments: ["terms", "complaints", "imprint"], cookies: ["privacy", "accessibility", "imprint"], complaints: ["returns", "warranty", "terms"], warranty: ["complaints", "returns", "terms"], accessibility: ["privacy", "cookies", "imprint"],
};

const germanDetailedPolicies: Partial<Record<PolicyKey, LegalSection[]>> = {
  terms: [
    { title: "1. Geltungsbereich und Kundenkreis", paragraphs: ["Diese Allgemeinen Geschäftsbedingungen gelten für Verträge über Container, Zubehör, Umbauten sowie vereinbarte Transport- und Aufstellleistungen. NORDIKA Container beliefert Unternehmen, öffentliche Auftraggeber und private Verbraucher.", "Zwingende gesetzliche Rechte von Verbrauchern bleiben unberührt. Besondere Vereinbarungen im konkreten Angebot oder in der Auftragsbestätigung gehen diesen allgemeinen Hinweisen vor."] },
    { title: "2. Angebot, Bestellung und Vertragsschluss", paragraphs: ["Katalog, Produktseite und Warenkorb stellen noch kein bindendes Lieferangebot dar. Der Warenkorb dient als unverbindliche Zusammenstellung. Verfügbarkeit, konkrete Ausführung, Lieferort, Entladung, Gesamtpreis und Lieferzeit werden in einem individuellen Angebot beziehungsweise einer Auftragsbestätigung festgehalten.", "Ein Vertrag kommt nach dem im konkreten Angebot beschriebenen Verfahren zustande. Änderungen und Nebenleistungen sind nur geschuldet, wenn sie bestätigt wurden."] },
    { title: "3. Preise, Transportkosten und Zahlung", paragraphs: ["Als Bruttopreis gekennzeichnete Produktpreise enthalten die deutsche Umsatzsteuer. Bei einer grenzüberschreitenden Lieferung an ein Unternehmen in einem anderen EU-Mitgliedstaat kann nach erfolgreicher Prüfung einer gültigen EU-USt-IdNr. und der tatsächlichen Beförderung in den anderen Mitgliedstaat eine innergemeinschaftliche Lieferung mit 0 % Umsatzsteuer abgerechnet werden. Andernfalls wird die anwendbare Umsatzsteuer berechnet. Lieferung, Kranentladung, Aufstellung, Umbauten und Zubehör sind nur enthalten, wenn sie ausdrücklich ausgewiesen sind.", "Transportkosten werden individuell anhand von Zielort, Strecke, Containergröße, Fahrzeug, Entladeart und Standortbedingungen berechnet. Zahlungsart, Fälligkeit und Bankverbindung ergeben sich ausschließlich aus Angebot, Auftragsbestätigung oder Rechnung."] },
    { title: "4. Lieferung und Mitwirkung am Standort", paragraphs: ["Die öffentlich zugänglichen Versand- und Lieferbedingungen erläutern Liefergebiete, Zeitspannen, Transport, Entladung und Standortanforderungen. Der Kunde muss richtige Lieferangaben, eine geeignete Zufahrt, ausreichend Rangier- und Entladeraum, tragfähigen Untergrund sowie erforderliche Genehmigungen bereitstellen.", "Eine Kranentladung oder besondere Ausrüstung gehört nur zum Auftrag, wenn sie ausdrücklich bestätigt ist. Gesetzliche Rechte wegen Lieferverzugs bleiben unberührt."] },
    { title: "5. Zustandsklassen und gebrauchte Container", paragraphs: ["Maßgeblich sind die vereinbarte Produktbeschreibung und Zustandsklasse. Im Projekt verwendete Bezeichnungen sind insbesondere Neu, One-Trip, Gebraucht, WWT, CW/Cargo Worthy und IICL, soweit sie beim konkreten Produkt angegeben sind.", "Dellen, Kratzer, Lackabrieb, reparierte Stellen, oberflächliche Korrosion und frühere Transportmarkierungen können bei gebrauchten Containern zustandstypisch sein und sind nicht automatisch ein Mangel. Der Container muss dennoch der ausdrücklich zugesagten Beschaffenheit entsprechen."] },
    { title: "6. Prüfung, Gefahr und Mängel", paragraphs: ["Verbraucher sollen sichtbare Transport- oder Übergabeschäden möglichst sofort dokumentieren; das Unterlassen nimmt ihnen nicht automatisch gesetzliche Mängelrechte. Ist der Kauf für beide Parteien ein Handelsgeschäft, gelten für Unternehmer die Untersuchungs- und Rügepflichten des § 377 HGB, soweit anwendbar.", "Bei einem berechtigten Mangel erfolgt zunächst die gesetzlich vorgesehene Nacherfüllung, etwa durch Nachbesserung oder Ersatzlieferung, soweit anwendbar. Notwendige Transportkosten werden nach den gesetzlichen Regeln getragen. Weitergehende Rechte, insbesondere Minderung, Rücktritt oder Schadensersatz, richten sich nach den gesetzlichen Voraussetzungen."] },
    { title: "7. Widerruf und Rückgabe", paragraphs: ["Ein gesetzliches Widerrufsrecht steht nur Verbrauchern und nur bei Vorliegen der gesetzlichen Voraussetzungen zu. Einzelheiten und mögliche Ausnahmen für eindeutig kundenspezifisch hergestellte Waren stehen in der Widerrufsbelehrung.", "Über gesetzliche Rechte hinaus besteht wegen Größe, Gewicht und erforderlichem Spezialtransport kein allgemeines freiwilliges Rückgaberecht. Jede Rücknahme und jeder Schwerlast-Rücktransport muss vorab mit NORDIKA Container abgestimmt werden."] },
  ],
  withdrawal: [
    { title: "Widerrufsrecht für Verbraucher", paragraphs: ["Verbraucher haben bei einem anwendbaren Fernabsatzvertrag grundsätzlich das Recht, den Vertrag binnen 14 Tagen ohne Angabe von Gründen zu widerrufen. Bei Kaufverträgen über Waren beginnt die Frist grundsätzlich an dem Tag, an dem der Verbraucher oder ein von ihm benannter, nicht als Beförderer tätiger Dritter die Ware erhalten hat.", "Der Widerruf muss durch eine eindeutige Erklärung an NORDIKA Container GmbH, Nikolaus-Otto-Str. 9, 55129 Mainz, E-Mail: info@nordikacontainer.com erfolgen. Zur Fristwahrung genügt die rechtzeitige Absendung. Das verlinkte Muster-Widerrufsformular kann verwendet werden, ist aber nicht vorgeschrieben."] },
    { title: "Folgen des Widerrufs", paragraphs: ["Bei einem wirksamen Widerruf werden die empfangenen Zahlungen einschließlich der Kosten der günstigsten angebotenen Standardlieferung nach den gesetzlichen Vorgaben spätestens binnen 14 Tagen ab Eingang des Widerrufs zurückgezahlt. Zusätzliche Kosten einer teureren, vom Verbraucher gewählten Lieferart werden nicht erstattet.", "Die Rückzahlung kann nach den gesetzlichen Voraussetzungen zurückgehalten werden, bis die Ware zurückerhalten wurde oder der Verbraucher den Nachweis der Rücksendung erbracht hat; dies gilt nicht, wenn NORDIKA Container die Abholung angeboten hat. Die Rückzahlung erfolgt grundsätzlich mit demselben Zahlungsmittel, sofern nichts anderes kostenfrei vereinbart wurde."] },
    { title: "Rücktransport von Containern", paragraphs: ["Container können wegen Größe und Gewicht nicht mit gewöhnlichen Paketdiensten zurückgesandt werden. Veranlassen Sie keinen eigenständigen Transport. NORDIKA Container koordiniert Abholung beziehungsweise Schwerlast-Rücktransport.", "Der Verbraucher trägt die unmittelbaren Rücksendekosten bei einem Widerruf nur, wenn er vor Vertragsschluss ordnungsgemäß darüber informiert wurde und NORDIKA Container die Kosten nicht übernommen hat. Die konkrete beziehungsweise gesetzlich erforderliche Kostenschätzung muss in den vor Vertragsschluss bereitgestellten Unterlagen für den jeweiligen Container und Lieferort ausgewiesen werden."] },
    { title: "Ausnahmen", paragraphs: ["Das Widerrufsrecht kann insbesondere bei Waren ausgeschlossen sein, die nicht vorgefertigt sind und für deren Herstellung eine individuelle Auswahl des Verbrauchers maßgeblich ist oder die eindeutig auf persönliche Bedürfnisse zugeschnitten sind. Das gilt nicht pauschal für jeden Container. Entscheidend sind der konkrete Vertrag und die tatsächlich vereinbarte Individualisierung.", "Unternehmern steht das gesetzliche Verbraucherwiderrufsrecht nicht zu. Gesetzliche Mängelrechte sind vom Widerrufsrecht unabhängig und bleiben unberührt."] },
  ],
  returns: [
    { title: "Kein allgemeines freiwilliges Rückgaberecht", paragraphs: ["Über die gesetzlichen Rechte hinaus bieten wir aufgrund der Größe, des Gewichts und des erforderlichen Spezialtransports der Container kein allgemeines freiwilliges Rückgaberecht für nicht mangelhafte Ware an.", "Eine freiwillige Rücknahme kann ausnahmsweise ausdrücklich schriftlich vereinbart werden. Vorher werden Transportorganisation, Kosten, mögliche Erstattung der ursprünglichen Lieferung und weitere vereinbarte Abzüge transparent festgehalten. Gesetzliche Verbraucher-, Widerrufs- und Mängelrechte werden dadurch nicht eingeschränkt."] },
    { title: "Gesetzlicher Widerruf von Verbrauchern", paragraphs: ["Bei einem anwendbaren Fernabsatzvertrag gilt für Verbraucher grundsätzlich die gesetzliche Widerrufsfrist von 14 Tagen ab dem gesetzlich maßgeblichen Warenempfang. Einzelheiten, Folgen, Rücktransportkosten und mögliche Ausnahmen für tatsächlich kundenspezifisch hergestellte Waren finden Sie in der verlinkten Widerrufsbelehrung.", "Eine kundenspezifische Ausnahme wird nicht pauschal auf alle Container angewendet. Sie kommt nur in Betracht, wenn die gesetzlichen Voraussetzungen beim konkreten Auftrag erfüllt sind."] },
    { title: "Prüfung bei Lieferung", paragraphs: ["Bitte prüfen Sie den Container während Lieferung und Entladung. Kontrollieren Sie Containerart, Größe, vereinbarten Zustand, sichtbare strukturelle oder transportbedingte Schäden, Türen und Verriegelungen sowie vereinbartes Zubehör oder Umbauten."], bullets: ["Fahrer sofort auf sichtbare Schäden hinweisen", "Übersichts- und Detailfotos anfertigen", "Schaden nach Möglichkeit auf den Lieferunterlagen vermerken", "NORDIKA Container unverzüglich unter Angabe der Auftragsnummer informieren"] },
    { title: "Falscher, abweichender oder beschädigter Container", paragraphs: ["Wurde die falsche Größe oder Containerart geliefert, weicht der Container wesentlich von der vereinbarten Beschreibung ab oder besteht ein erheblicher Transportschaden, kontaktieren Sie NORDIKA Container sofort. Soweit rechtlich gerechtfertigt, kann eine erkennbar fehlerhafte Lieferung bei Übergabe zurückgewiesen werden.", "Organisieren Sie keinen eigenen Rücktransport. Senden Sie Auftrags- oder Rechnungsnummer, eine Beschreibung sowie aussagekräftige Fotos oder Videos. Wir prüfen die Meldung und koordinieren die nächsten Schritte."] },
    { title: "Lösung bei berechtigter Beanstandung", paragraphs: ["Bei einer berechtigten Beanstandung kommen nach den gesetzlichen Voraussetzungen Nachbesserung, Ersatzlieferung, Abholung beziehungsweise Rücktransport, Minderung oder Erstattung in Betracht. NORDIKA Container darf grundsätzlich zunächst die gesetzlich vorgesehene Nacherfüllung prüfen und durchführen, soweit kein gesetzlicher Ausnahmefall vorliegt.", "Ist der Container mangelhaft, weicht er wesentlich vom Auftrag ab oder liegt ein zurechenbarer qualifizierter Transportschaden vor, organisiert NORDIKA Container die erforderliche Abholung beziehungsweise den Rücktransport und trägt die notwendigen Transportkosten nach Maßgabe des Gesetzes."] },
    { title: "Verdeckte oder später erkennbare Mängel", paragraphs: ["Mängel, die bei der Übergabe vernünftigerweise nicht erkennbar waren, sollen nach Entdeckung zeitnah gemeldet werden. Bitte nennen Sie Auftrags- oder Rechnungsnummer, Art des Problems, Entdeckungsdatum und fügen Sie bei Bedarf Fotos oder Videos bei.", "Die Annahme oder Entladung bestätigt nicht, dass keinerlei verdeckte Mängel bestehen. Gesetzliche Gewährleistungsrechte bleiben unberührt. Bei beiderseitigen Handelsgeschäften gelten für Unternehmer die Untersuchungs- und Rügepflichten des § 377 HGB, soweit anwendbar."] },
    { title: "Gebrauchte Container", paragraphs: ["Gebrauchte Container können je nach vereinbarter Zustandsklasse Dellen, Kratzer, Lackabrieb, reparierte Bereiche, Oberflächenkorrosion oder frühere Transportmarkierungen aufweisen. Solche zustandstypischen Gebrauchsspuren sind nicht automatisch ein Mangel, wenn sie dem beworbenen und vereinbarten Zustand entsprechen.", "Verwendete Zustandsangaben können Neu, One-Trip, Gebraucht, WWT, CW/Cargo Worthy oder IICL sein. Maßgeblich ist ausschließlich die konkrete Produktbeschreibung und schriftliche Vereinbarung."] },
    { title: "Kosten und Erstattung", paragraphs: ["Bei einem berechtigten Mangel oder einer NORDIKA Container zuzurechnenden Falschlieferung organisiert NORDIKA Container den notwendigen Rücktransport und trägt die gesetzlich erforderlichen Kosten. Bei einem wirksamen Verbraucherwiderruf gelten die in der Widerrufsbelehrung und den vor Vertragsschluss erteilten Informationen genannten Kostenregeln.", "Bei einer ausnahmsweise vereinbarten freiwilligen Rücknahme nicht mangelhafter Ware werden Organisation, Rücktransportkosten, ursprüngliche Lieferkosten und mögliche weitere Kosten vorab schriftlich vereinbart. Eine geschuldete Rückzahlung erfolgt nach Prüfung und nach den gesetzlichen beziehungsweise ausdrücklich vereinbarten Fristen."] },
    { title: "Internationale Rückgaben", paragraphs: ["Für Lieferungen außerhalb Deutschlands gelten dieselben Melde- und Dokumentationsschritte. Der Zeitraum eines anwendbaren Verbraucherwiderrufs wird nach den gesetzlichen Regeln ab Erhalt der Ware berechnet, nicht pauschal ab Bestelldatum.", "Veranlassen Sie keinen eigenständigen grenzüberschreitenden Rücktransport eines mehrere Tonnen schweren Containers. Bei einer berechtigten Beanstandung koordiniert NORDIKA Container die notwendige Rückführung. Bei anderen Rückgabegründen werden Route, Zuständigkeit und Kosten vorab geklärt."] },
  ],
  payments: [
    { title: "Checkout und verbindliche Zahlungsinformationen", paragraphs: ["Im Checkout können Kunden eine Bestellung mit genauer Lieferadresse, gewünschter Entladeart und Zahlungswunsch übermitteln. Zur Auswahl stehen eine Rechnung zur anschließenden Bestätigung oder eine SEPA-Zahlungsanforderung. Der angezeigte Warenwert basiert auf den aktuellen Produktpreisen; Verfügbarkeit, Umsatzsteuerbehandlung und Transportkosten werden vor der Zahlungsaufforderung geprüft.", "Bankverbindung, endgültiger Gesamtbetrag, Fälligkeit und Zahlungsbedingungen werden ausschließlich in der anschließend versandten Rechnung, Auftragsbestätigung oder SEPA-Zahlungsanforderung mitgeteilt. Zahlen Sie nicht allein aufgrund der vorläufigen Checkout-Zusammenfassung."] },
    { title: "Gesamtpreis vor Vertragsschluss", paragraphs: ["Als Bruttopreis gekennzeichnete Produktpreise enthalten die deutsche Umsatzsteuer. Bei einer innergemeinschaftlichen Lieferung an ein Unternehmen in einem anderen EU-Mitgliedstaat wird der Nettowarenwert mit 0 % Umsatzsteuer ausgewiesen, sobald eine gültige EU-USt-IdNr. und die grenzüberschreitende Beförderung erfolgreich geprüft wurden. Individuelle Transportkosten, Entladung, Kran, Aufstellung, Zubehör und Umbauten werden gesondert ausgewiesen, soweit sie nicht ausdrücklich im Produktpreis enthalten sind. Der bestätigte Gesamtpreis ist vor Vertragsschluss ersichtlich."] },
    { title: "Zahlungsprüfung", paragraphs: ["Bitte gleichen Sie Empfänger, Rechnung, Auftragsnummer, Betrag und Verwendungszweck ab. Unerwartete Änderungen von Bankdaten sollten Sie vor Zahlung über die bekannten Kontaktdaten von NORDIKA Container verifizieren. Bewahren Sie den Zahlungsbeleg für Rückfragen auf."] },
    { title: "Erstattungen", paragraphs: ["Erstattungen bei Widerruf, berechtigten Mängeln oder ausdrücklich vereinbarten Rücknahmen richten sich nach der jeweiligen Rechtsgrundlage und den schriftlichen Vertragsunterlagen. Die Rückgabe- und Erstattungsrichtlinie sowie die Widerrufsbelehrung erläutern die jeweiligen Abläufe."] },
  ],
};

export function getLegalCopy(locale: Locale, key: RouteKey): LegalCopy | undefined {
  if (!(key in titles[locale])) return undefined;
  const legalKey = key as LegalKey;
  const labels = ui[locale];
  const contact = `${SITE.legalName}\n${SITE.address.street}\n${SITE.address.postalCode} ${SITE.address.city}\n${SITE.email}\n${SITE.phone}`;
  const detailed = locale === "de" && legalKey !== "imprint" ? germanDetailedPolicies[legalKey] : undefined;
  const sections: LegalSection[] = legalKey === "imprint"
    ? [
        { title: labels.provider, paragraphs: [`${SITE.legalName}\n${SITE.address.street}\n${SITE.address.postalCode} ${SITE.address.city}\nDeutschland`] },
        { title: labels.contact, paragraphs: [`Telefon: ${SITE.phone}\nE-Mail: ${SITE.email}\nWeb: ${SITE.url.replace(/^https?:\/\//, "")}`] },
        { title: registerTitle[locale], paragraphs: [`${SITE.commercialRegisters.map((entry) => `${entry.court}: ${entry.number}`).join("\n")}\nEUID: ${SITE.euid}\nUSt-IdNr.: ${SITE.vatId}`] },
      ]
    : detailed
      ? [...detailed, { title: labels.contact, paragraphs: [contact, labels.contract] }]
      : [
        { title: labels.coverage, paragraphs: [summaries[locale][legalKey]], bullets: actions[locale][legalKey] },
        { title: labels.contact, paragraphs: [contact, labels.contract] },
      ];
  const intro = legalKey === "imprint" ? labels.intro : summaries[locale][legalKey];
  return { eyebrow: labels.eyebrow, title: titles[locale][legalKey], intro, sections, related: related[legalKey] };
}

export function LegalPage({ locale, copy }: { locale: Locale; copy: LegalCopy }) {
  return <main><Breadcrumbs locale={locale} items={[{ label: copy.title }]} /><PageHero eyebrow={copy.eyebrow} title={copy.title} intro={copy.intro} /><article className="section-space bg-white"><div className="container-shell max-w-4xl">{copy.sections.map((section, index) => <section key={`${section.title}-${index}`} className="border-b border-zinc-200 py-8 first:pt-0 last:border-0"><h2 className="text-2xl font-extrabold">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-4 whitespace-pre-line leading-8 text-zinc-600">{paragraph}</p>)}{section.bullets && <ul className="mt-6 grid gap-3 sm:grid-cols-2">{section.bullets.map((bullet) => <li key={bullet} className="flex items-start gap-3"><span className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#ffb33e]"><Check className="h-3 w-3 text-[#092b4e]" /></span><span>{bullet}</span></li>)}</ul>}</section>)}<aside className="mt-10 bg-zinc-100 p-7"><h2 className="text-2xl font-extrabold">{ui[locale].related}</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{copy.related.map((key) => <Link key={key} href={href(locale, key)} className="inline-flex items-center justify-between gap-3 bg-white px-4 py-3 font-bold text-primary hover:bg-secondary">{titles[locale][key]}<ArrowRight className="h-4 w-4 shrink-0" /></Link>)}</div></aside></div></article></main>;
}
