export const IMAGES = {
  hero: "/images/nordika-hero.png",
  container40hc: "/images/container-40hc.png",
  categorySea: "/images/categories/sea-container.jpg",
  categoryStorage: "/images/categories/storage-container.jpg",
  categoryRefrigerated: "/images/categories/refrigerated-container.jpg",
  categoryOpenSide: "/images/categories/open-side-container.jpg",
  categoryConversions: "/images/categories/container-conversions.png",
  typeShipping: "/images/container-types/shipping-containers.jpg",
  typeHighCube: "/images/container-types/high-cube-container.jpg",
  typeOpenSide: "/images/container-types/open-side-container.jpg",
  typeRefrigerated: "/images/container-types/refrigerated-container.jpg",
  typeOffice: "/images/container-types/office-container.webp",
  homeProcess: "/images/homepage/from-selection-to-installation.webp",
  homeDelivery: "/images/homepage/delivery-installation.webp",
  homeMainz: "/images/homepage/nordika-container-mainz.jpg",
} as const;
