import type { Locale } from "@/lib/i18n";

export const guideSectionCopy: Record<Exclude<Locale, "de">, Record<string, string>> = {
  en: {
    choose: "Start with intended use, required internal volume, door access and available site space. Standard containers cover many storage needs; high-cube models provide extra height for bulky goods or conversions.",
    condition: "One-trip units offer a very good appearance. Used wind- and watertight containers can be economical when dents, rust and paint marks are acceptable for the intended use.",
    delivery: "The product price is only one part of the project. Distance, access, unloading method and site preparation affect logistics, so provide photos and location details before ordering.",
    sizes: "A 20-foot container is compact and versatile, while a 40-foot unit provides roughly twice the floor length. Smaller models can suit restricted sites; actual stock varies.",
    height: "High-cube containers provide about 30 centimetres more external and internal height than many standard models. Allow for this when checking gates, bridges and overhead obstacles.",
    measure: "Actual external, internal and door dimensions can vary slightly by series. Use the measurements on the individual product page and verify critical clearances before ordering.",
    oneTrip: "One-trip containers have generally completed only one loaded journey. Light handling marks are possible, but the overall finish is normally much cleaner than on long-used equipment.",
    used: "WWT is used for wind- and watertight storage condition. Cargo-worthy refers to a unit assessable for freight use. Dents, corrosion and coating repairs are normal signs of use.",
    inspect: "Clarify weather-tightness, door operation, floor condition, CSC status, depot and current images. The right grade depends on the actual use, not on the label alone.",
    access: "The lorry and any crane need sufficient width, height and manoeuvring space. Record gates, bends, branches, cables, slopes and parked vehicles along the complete access route.",
    ground: "The position should be level and load-bearing. A container is normally supported at suitable points beneath its corner castings so the frame remains stable and the doors can operate freely.",
    crane: "Crane reach, obstacles, lifting direction and final door orientation determine the unloading solution. Photos, measurements and a simple site plan help the logistics review.",
  },
  nl: {
    choose: "Begin bij gebruik, benodigd binnenvolume, deurtoegang en beschikbare plaats. Standaardcontainers dekken veel opslagbehoeften; high cube biedt extra hoogte voor grote goederen of ombouw.",
    condition: "One-tripcontainers hebben een zeer goede uitstraling. Gebruikte wind- en waterdichte containers zijn economisch wanneer deuken, roest en verfsporen voor het gebruik aanvaardbaar zijn.",
    delivery: "De productprijs is slechts een deel van het project. Afstand, toegang, losmethode en voorbereiding beïnvloeden de logistiek; stuur daarom foto's en locatiegegevens vóór de bestelling.",
    sizes: "Een 20-voetscontainer is compact en veelzijdig, een 40-voetsmodel biedt ongeveer de dubbele vloerlengte. Kleinere modellen kunnen op beperkte locaties passen; voorraad wisselt.",
    height: "High-cubecontainers bieden ongeveer 30 centimeter extra buiten- en binnenhoogte ten opzichte van veel standaardmodellen. Houd hier rekening mee bij poorten en obstakels boven de route.",
    measure: "Buiten-, binnen- en deurmaten kunnen per serie iets variëren. Gebruik de maten op de productpagina en controleer kritieke doorgangen vóór bestelling.",
    oneTrip: "One-tripcontainers hebben doorgaans één beladen reis gemaakt. Lichte handlingsporen zijn mogelijk, maar de afwerking is meestal veel netter dan bij langdurig gebruikte units.",
    used: "WWT wordt gebruikt voor wind- en waterdichte opslagstaat. Cargo worthy betreft beoordeling voor vrachtgebruik. Deuken, corrosie en lakreparaties zijn normale gebruikssporen.",
    inspect: "Controleer dichtheid, deuren, vloer, CSC-status, depot en actuele foto's. De juiste klasse hangt af van het werkelijke gebruik, niet alleen van het label.",
    access: "Vrachtwagen en kraan hebben voldoende breedte, hoogte en manoeuvreerruimte nodig. Leg poorten, bochten, takken, kabels, hellingen en voertuigen over de hele route vast.",
    ground: "De locatie moet vlak en draagkrachtig zijn. Een container wordt normaal op geschikte punten onder de hoekstukken ondersteund zodat het frame stabiel blijft en deuren vrij werken.",
    crane: "Kraanbereik, obstakels, hijsrichting en gewenste deuroriëntatie bepalen de losoplossing. Foto's, maten en een eenvoudige plattegrond ondersteunen de beoordeling.",
  },
  it: {
    choose: "Parti da uso, volume interno, accesso alle porte e spazio disponibile. I container standard coprono molte esigenze di deposito; gli high cube offrono altezza extra per merci ingombranti o trasformazioni.",
    condition: "I one trip hanno un ottimo aspetto. I container usati resistenti a vento e acqua sono economici quando ammaccature, ruggine e segni di vernice sono accettabili per l'uso.",
    delivery: "Il prezzo del prodotto è solo una parte del progetto. Distanza, accesso, scarico e preparazione incidono sulla logistica; invia foto e dati del sito prima dell'ordine.",
    sizes: "Un 20 piedi è compatto e versatile, mentre un 40 piedi offre circa il doppio della lunghezza utile. Modelli più piccoli possono adattarsi a spazi limitati; lo stock varia.",
    height: "Gli high cube offrono circa 30 centimetri di altezza esterna e interna in più rispetto a molti standard. Consideralo per cancelli, ponti e ostacoli sopra il percorso.",
    measure: "Misure esterne, interne e delle porte possono variare leggermente per serie. Usa i dati della pagina prodotto e verifica i passaggi critici prima dell'ordine.",
    oneTrip: "I container one trip hanno in genere effettuato un solo viaggio carico. Sono possibili lievi segni di movimentazione, ma la finitura è normalmente molto più pulita dell'usato prolungato.",
    used: "WWT indica la condizione resistente a vento e acqua per deposito. Cargo worthy riguarda la valutazione per trasporto merci. Ammaccature, corrosione e riprese di vernice sono normali.",
    inspect: "Chiarisci tenuta, porte, pavimento, CSC, deposito e foto attuali. La classe corretta dipende dall'uso reale, non solo dall'etichetta.",
    access: "Mezzo e gru richiedono larghezza, altezza e spazio di manovra. Documenta cancelli, curve, rami, cavi, pendenze e veicoli lungo l'intero accesso.",
    ground: "Il posto deve essere piano e portante. Il container viene normalmente sostenuto sotto gli angolari con punti idonei, mantenendo stabile il telaio e libere le porte.",
    crane: "Portata della gru, ostacoli, direzione di sollevamento e orientamento delle porte determinano lo scarico. Foto, misure e planimetria aiutano la verifica.",
  },
  cs: {
    choose: "Začněte využitím, potřebným objemem, přístupem dveřmi a prostorem. Standardní kontejnery pokryjí mnoho skladových potřeb; high cube nabízí výšku navíc pro objemné zboží či úpravy.",
    condition: "One-trip kusy mají velmi dobrý vzhled. Použité kontejnery odolné proti větru a vodě jsou úsporné, pokud jsou pro využití přijatelné důlky, koroze a stopy laku.",
    delivery: "Cena produktu je jen část projektu. Vzdálenost, příjezd, vykládka a příprava místa ovlivňují logistiku; před objednávkou zašlete fotografie a údaje místa.",
    sizes: "Dvacetistopý kontejner je kompaktní a univerzální, čtyřicetistopý nabízí zhruba dvojnásobnou délku podlahy. Menší modely se hodí do omezených míst; sklad se mění.",
    height: "High-cube kontejnery mají oproti mnoha standardním modelům asi o 30 centimetrů větší vnější i vnitřní výšku. Zohledněte to u bran a překážek nad trasou.",
    measure: "Vnější, vnitřní a dveřní rozměry se mohou podle série mírně lišit. Použijte údaje konkrétního produktu a před objednávkou ověřte kritické průjezdy.",
    oneTrip: "One-trip kontejnery obvykle absolvovaly jednu naloženou cestu. Lehké stopy manipulace jsou možné, celková povrchová úprava však bývá výrazně čistší než u dlouhodobě používaných kusů.",
    used: "WWT se používá pro skladovací stav odolný proti větru a vodě. Cargo worthy se týká posouzení pro nákladní dopravu. Důlky, koroze a opravy laku jsou běžné.",
    inspect: "Ověřte těsnost, dveře, podlahu, CSC, depo a aktuální fotografie. Správná třída závisí na skutečném využití, nikoli jen na označení.",
    access: "Nákladní vozidlo a jeřáb potřebují šířku, výšku a manipulační prostor. Zdokumentujte brány, zatáčky, větve, vedení, svahy a vozidla po celé trase.",
    ground: "Místo má být rovné a únosné. Kontejner se běžně podpírá vhodnými body pod rohovými prvky, aby rám zůstal stabilní a dveře pracovaly volně.",
    crane: "Dosah jeřábu, překážky, směr zvedání a orientace dveří určují vykládku. Fotografie, rozměry a jednoduchý plánek usnadní posouzení.",
  },
  es: {
    choose: "Empieza por uso, volumen interior, acceso por puertas y espacio disponible. Los estándar cubren muchas necesidades de almacén; high cube aporta altura para mercancía voluminosa o transformaciones.",
    condition: "Los one trip ofrecen muy buen aspecto. Los usados resistentes al viento y agua son económicos cuando abolladuras, óxido y marcas de pintura son aceptables para el uso.",
    delivery: "El precio del producto es solo una parte del proyecto. Distancia, acceso, descarga y preparación afectan a la logística; envía fotos y datos del lugar antes de pedir.",
    sizes: "Un contenedor de 20 pies es compacto y versátil, mientras uno de 40 ofrece aproximadamente el doble de longitud de suelo. Los modelos pequeños sirven para espacios limitados; el stock varía.",
    height: "Los high cube aportan unos 30 centímetros más de altura exterior e interior que muchos modelos estándar. Tenlo en cuenta en portones, puentes y obstáculos sobre la ruta.",
    measure: "Las medidas exteriores, interiores y de puertas pueden variar ligeramente por serie. Usa los datos del producto y comprueba pasos críticos antes de pedir.",
    oneTrip: "Los one trip suelen haber realizado un solo viaje con carga. Puede haber marcas leves de manejo, pero el acabado normalmente es mucho más limpio que en equipos usados durante años.",
    used: "WWT se usa para estado resistente al viento y agua para almacén. Cargo worthy se refiere a evaluación para carga. Abolladuras, corrosión y reparaciones de pintura son normales.",
    inspect: "Aclara estanqueidad, puertas, suelo, CSC, depósito y fotos actuales. El grado adecuado depende del uso real, no solo de la etiqueta.",
    access: "Camión y grúa necesitan anchura, altura y espacio de maniobra. Documenta portones, curvas, ramas, cables, pendientes y vehículos en toda la ruta.",
    ground: "El lugar debe estar nivelado y ser portante. El contenedor suele apoyarse bajo las cantoneras en puntos adecuados para mantener el bastidor estable y las puertas libres.",
    crane: "Alcance de la grúa, obstáculos, dirección de izado y orientación de puertas determinan la descarga. Fotos, medidas y un plano sencillo ayudan a revisarla.",
  },
};
